---

- name: set timezone
  timezone:
    name: "{{ baselinux_timezone }}"
  notify:
    - restart rsyslog

- name: selinux permissive
  selinux:
    policy: targeted
    state: "{{ baselinux_selinux_mode }}"

- name: modify ulimit default parameters
  copy:
    src: files/limits.conf
    dest: /etc/security/limits.conf
    mode: 0644

- name: configure ssh client
  template:
    src: templates/ssh_config.j2
    dest: /etc/ssh/ssh_config

- name: configure sshd
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify:
    - restart sshd

- name: set root password
  shell: echo '{{ baselinux_root_passwd }}' | passwd root --stdin

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install baselinux packages
  yum:
    name: "{{ baselinux_pkgs }}"
    state: latest

- name: generate figlet banner
  shell: figlet {{ baselinux_figlet_string }}
  register: figlet_string

- set_fact:
    baselinux_motd_banner: "{{ figlet_string.stdout }}"

- name: configure motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: start/enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

- name: disable dns automatic configuration by NetworkManager
  copy:
    src: files/disable-resolve.conf-managing.conf
    dest: /etc/NetworkManager/conf.d/disable-resolve.conf-managing.conf
  notify:
    - restart NetworkManager

- name: configure resolv.conf
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf

