all:
  hosts:
    k8s_1:
      ansible_host: ${k8s_1}
    k8s_2:
      ansible_host: ${k8s_2}
    k8s_3:
      ansible_host: ${k8s_3}
  children:
    k8s_cluster:
      hosts:
        k8s_1:
          kubernetes_init: yes
        k8s_2:
        k8s_3:
    k8s_master:
      vars:
        kubernetes_master: yes
      hosts:
        k8s_1:
    k8s_worker:
      vars:
        kubernetes_worker: yes
      hosts:
        k8s_2:
        k8s_3:
