galaxy_info:
  author: Irakli Korpashvili
  description: Provisions Kubernetes on CentOS 7.
  company: Nandi

  license: BSD

  min_ansible_version: 2.4

  platforms:
  - name: CentOS
    versions:
    - 7
